### ISSUE TITLE
Can i show some 3d models in space without markers?

### ISSUE THREAD

**Issue by dj-fiorex** [ToughNutToCrack/ARWT#13]
Hello everyone and congratulations for the work you are doing.
I would like to develop a simple AR scene that displays 3D models in space always in the same position (for example one at 60 degrees, one at 200 etc.) without using the marker. is there a way to do this with ARWT?

Thanks!

**Comment by RedSimurgh** [comment]
Use WebXR for surface detection

https://github.com/De-Panther/unity-webxr-export

**Comment by kevinjoel2A** [comment]
hi everone..
https://github.com/De-Panther/unity-webxr-export
please solve this or suggest any other idea for webar for unity3d

**Comment by doJester13** [comment]
Hi, ARWT already supports this feature.
At the moment, we support features from ARjs and WebXR.
In particular, about WebXR, we support anchors, hit-testing, and image tracking (experimental).
