### ISSUE TITLE
FileNotFoundException: Could not find file "D:\RJProject\ARWTCrashDemo-main\build\Build\UnityLoader.js"

### ISSUE THREAD

**Issue by iluvian** [ToughNutToCrack/ARWT#33]
Hey, guys! Really glad to have an example of a webar project that works for both ios and android. But I've stuck with one thing: when I try to simply export your app from unity to web gl - I have just camera working and that's all, no ui, no objects etc. Same story with a dancing guy - just camera. What am I doing wrong?
![20221230-162226](https://user-images.githubusercontent.com/39895100/210049713-c792fad1-71a2-404a-88db-cff12bb18149.jpg)

**Comment by afzaale01** [comment]
How @iluvian you handled it ?

**Comment by Trey-S** [comment]
@iluvian  @afzaale01 what was the solution to this? I'm having the same issue.
