### ISSUE TITLE
Particular setup for iOS devices?

### ISSUE THREAD

**Issue by Reddevildragg** [ToughNutToCrack/ARWT#7]
Hi

Just wondering if there is any special setup that is required for iOS devices (regardless of browser).

I have been running the demo scenes and on android all works perfectly, but on iOS the camera comes on, but will not track/load the model when looking at the marker. Just wondering if there is anything in particular that I need to set up (or if its a limitation of the platform at present)

**Comment by Sov3rain** [comment]
Did you try to look into the debug console for error messages? On mobile you can go to `chrome://inspect` on any chromium based browser and link your device for remote logging.

**Comment by Reddevildragg** [comment]
Could not see anything that jumps out at me, ill do another test this week and have a closer inspection of the error console and update afterwards

**Comment by Reddevildragg** [comment]
Tried it on a couple more devices and with the logs, can not replicate apart from the 1 device so going to assume its a device issue for now
